# Generated by Django 4.2.3 on 2023-07-20 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('', 'normal'), ('', 'low')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
